---
name: Tests

on:
  push:

jobs:
  run:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        powerdns-versions: ['42', '43', '44', '45', '46', '47']
        php-versions: ['7.3', '7.4', '8.0', '8.1']
    services:
      powerdns:
        image: registry.exonet.nl/exonet/powerdns-test:${{ matrix.powerdns-versions}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        run: ./vendor/bin/phpunit
